;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fib [n]
  (if (<= n 1) n
    (+ (fib (- n 1)) (fib (- n 2)))))

(defn fibs [lim]
  (loop [rs [], n 0]
    (let [r (fib n)]
      (if (> r lim) rs
        (recur (conj rs r) (inc n))))))

(println
  (reduce
    +
    (filter even? (fibs 4000000))))
